; Spotify for Windows (64 bit)
; Patch signatures live in ./patches/native.ini and ./patches/frontend.ini.

[Spotify]
Version=1.2.93.667

[PatchFiles]
Native=./patches/native.ini
Frontend=./patches/frontend.ini

; 0 Disable
; 1 Information
; 2 Debug
[Log]
Level=0

; Debug=1 also forces Log Level=2 and enables frontend dump helpers.
[Debug]
Enable=0

[URL_block]
Enable=1
1=/ads/
2=/ad-logic/
3=/gabo-receiver-service/
4=/desktop-update/

[LIBCEF]
Block_crashpad=1
CEF_REQUEST_GET_URL_OFFSET=48
CEF_ZIP_READER_GET_READ_FILE_OFFSET=112
CEF_ZIP_READER_GET_FILE_NAME_OFFSET=72
