#!/usr/bin/env python3
"""Print the readable source's INI patch for Spotify 1.3.1.234's About dialog."""
import json


PLATFORMS = [
    ('Win32', 'win-x86'),
    ('Win32_x86_64', 'win-x86-64'),
    ('Win32_ARM64', 'win-arm-64'),
    ('OSX', 'mac-x86'),
    ('OSX_ARM64', 'mac-arm-64'),
    ('Linux', 'linux'),
]
CREDITS_HTML = (
    "\n\n<a href='https://github.com/Nuzair46/BlockTheSpot'>BlockTheSpot</a>"
    " | <a href='https://discord.gg/eYudMwgYtY'>Discord</a>"
)

# Factor the repeated translation prefix to make room inside the original read.
# The Map retains every platform entry; its extra property stores the credits.
ORIGINAL_MAP = 'let k=new Map([' + ','.join(
    f'[{json.dumps(platform)},u.Ru.get("desktop-about.platform-{label}")]'
    for platform, label in PLATFORMS
) + '])'
COMPACT_MAP = 'new Map([' + ','.join(json.dumps(platform) for platform, _ in PLATFORMS) + (
    '].map((e,t)=>[e,u.Ru.get("desktop-about.platform-"+['
) + ','.join(json.dumps(label) for _, label in PLATFORMS) + '][t])]))'
REPLACEMENT_MAP = f'let k=Object.assign({COMPACT_MAP},{{about:{json.dumps(CREDITS_HTML)}}})'


ORIGINAL_CREDITS = (
    '(0,r.jsx)(a.E,{as:"div",variant:"marginal",className:"ygMJjV5Q7D1aAn6f6lwZ",'
    'children:(0,r.jsx)(A.y,{source:u.Ru.get("about.copyright",p),'
    'paragraphClassName:"MdsFyvm9tgNhU8Tpm6IV"})})'
)
# jsx does not use a receiver. Removing its two comma expressions saves the
# eight bytes needed for +k.about, while preserving Spotify's HTML-to-React renderer.
REPLACEMENT_CREDITS = ORIGINAL_CREDITS.replace('(0,r.jsx)(', 'r.jsx(').replace(
    'source:u.Ru.get("about.copyright",p)', 'source:u.Ru.get("about.copyright",p)+k.about'
)


def patches():
    result = []
    for original, replacement in [(ORIGINAL_MAP, REPLACEMENT_MAP),
                                  (ORIGINAL_CREDITS, REPLACEMENT_CREDITS)]:
        before, after = original.encode(), replacement.encode()
        if len(after) > len(before):
            raise ValueError('About patch exceeds its original byte range')
        result.append((before, after.ljust(len(before), b' ')))
    return result


def ini_section():
    lines = ['[about_blockthespot]',
             '; Generated by tools/generate_about_patch.py; both writes are one transaction.']
    for i, (signature, value) in enumerate(patches(), 1):
        lines += [f'Signature_{i}={signature.hex(" ").upper()}',
                  f'Value_{i}={value.hex(" ").upper()}', f'Offset_{i}=0']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    print(ini_section(), end='')
